# Generated by Django 4.2.3 on 2024-08-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='is_correct',
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
